<?php

namespace App\Controller;

use App\Entity\PostLike;
use App\Entity\Publication;
use App\Entity\User;
use App\Form\PublicationType;
use App\Repository\PostLikeRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Form\CommentaireType;
use App\Repository\PublicationRepository;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\DateTime;

class PublicationController extends AbstractController
{
    /**
     * @Route("/publication", name="publication")
     */
    public function index(): Response
    {
        return $this->render('publication/affichefronP.html.twig', [
            'controller_name' => 'PublicationController',
        ]);
    }

    /**
     * @Route("/afficheP", name="afficheP")
     */
    public function afficheP(): Response
    {
        //rÃƒÂ©cupÃƒÂ©rer le repository pour utiliser la fonction findAll
        $r=$this->getDoctrine()->getRepository(Publication::class);
        //faire appel Ãƒ  la fonction findAll()
        $publications=$r->findAll();

        //ou $r=$this->getDoctrine()->getRepository(Classroom::class)->findAll();
        return $this->render('publication/afficheP.html.twig', [
            'p' => $publications,
        ]);
    }

    /**
     * @Route("/affichefronP", name="affichefronP")
     */
    public function affichefronP(): Response
    {
        //rÃƒÂ©cupÃƒÂ©rer le repository pour utiliser la fonction findAll
        $r=$this->getDoctrine()->getRepository(Publication::class);
        //faire appel Ãƒ  la fonction findAll()
        $publications=$r->findAll();

        //ou $r=$this->getDoctrine()->getRepository(Classroom::class)->findAll();
        return $this->render('publication/affichefronP.html.twig', [
            'p' => $publications,
        ]);
    }



    /**
     * @Route("/suppP/{id}", name="suppPP")
     */
    public function supp($id): Response

    {
        //rÃ©cupÃ©rer le classroom Ã  supprimer
        $publications=$this->getDoctrine()->getRepository(Publication::class)->find($id);
        //on passe Ã  la suppression
        $em=$this->getDoctrine()->getManager();
        $em->remove($publications);
        $em->flush();

        return $this->redirectToRoute('afficheP');
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
    /**
     * @Route("/ajoutP", name="ajoutP")
     */
    public function ajoutP(Request $request): Response
    {
        //crÃƒÂ©ation du formulaire
        $p = new Publication();
        $form = $this->createForm(PublicationType::class, $p);
        //rÃƒÂ©cupÃƒÂ©rer les donnÃƒÂ©es saisies depuis la requete http
        $form->handleRequest($request);
        if ($form->isSubmitted()&& $form->isValid()) {
            $file = $form->get('image')->getData();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('brochures_directory'),
                $fileName
            );

            $p->setImage($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($p);
            $em->flush();
            return $this->redirectToRoute('afficheP');
        }

        return $this->render('publication/ajoutP.html.twig', [
            'f' => $form->createView(),

        ]);
    }

    /**
     * @Route("/ajoutfronP", name="ajoutfronP")
     */
    public function ajoutfronP(Request $request): Response
    {
        //crÃƒÂ©ation du formulaire
        $p = new Publication();
        $form = $this->createForm(PublicationType::class, $p);
        //rÃƒÂ©cupÃƒÂ©rer les donnÃƒÂ©es saisies depuis la requete http
        $form->handleRequest($request);
        if ($form->isSubmitted()&& $form->isValid()) {
            $file = $form->get('image')->getData();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('brochures_directory'),
                $fileName
            );

            $p->setImage($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($p);
            $em->flush();
            return $this->redirectToRoute('affichefronP');
        }

        return $this->render('publication/ajoutfronP.html.twig', [
            'f' => $form->createView(),
        ]);

    }
    /**
     * @Route("/suppfronP/{id}", name="suppfronP")
     */
    public function suppfron($id): Response

    {
        //rÃ©cupÃ©rer le classroom Ã  supprimer
        $publications=$this->getDoctrine()->getRepository(Publication::class)->find($id);
        //on passe Ã  la suppression
        $em=$this->getDoctrine()->getManager();
        $em->remove($publications);
        $em->flush();

        return $this->redirectToRoute('affichefronP');
    }

    /**
     * @Route("/modiffronP/{id}", name="modiffronP")
     */
    public function modifP(Request $request,$id): Response
    {
        //rÃƒÂ©cupÃƒÂ©rer le classroom ÃƒÂ  modifier
        $publications=$this->getDoctrine()->getRepository(Publication::class)->find($id);
        //crÃƒÂ©ation du formulaire rempli
        $form=$this->createForm(PublicationType::class,$publications);
        //rÃƒÂ©cupÃƒÂ©rer les donnÃƒÂ©es saisies depuis la requete http
        $form->handleRequest($request);
        if($form->isSubmitted())
        {
            $file = $form->get('image')->getData();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('brochures_directory'),
                $fileName
            );

            $publications->setImage($fileName);

            $em=$this->getDoctrine()->getManager();

            $em->flush();
            return $this->redirectToRoute('affichefronP');
        }

        return $this->render('publication/ajoutP.html.twig', [
            'f' => $form->createView(),
        ]);
    }
    /**
     * Permet de liker ou unliker un publication
     *
     * @Route ("/publication/{id}/like", name="PosteLike")
     * @param Publication $publication
     * @param PostLikeRepository $likeRepository
     * @param EntityManagerInterface $manager
     * @param
     * @return Response
     */

    public function like(Publication $publication,PostLikeRepository $likeRepository,EntityManagerInterface $manager,$id):Response
    {

        // $user = $this->getUser();

        $idu=1; //id ta3 utilisateur
        $user = $this->getDoctrine()->getRepository(User::class)->find($idu);
        //   $publications=$this->getDoctrine()->getRepository(Publications::class)->find($id);


        if (!$user) return $this->json([
            'code' => 403,
            'message' => "Unauthorized"
        ], 403);



        if($publication->JaimePar($user)) {
            $like = $likeRepository->findOneBy ([
                'post' => $publication,
                'user' => $user

            ]);
            $manager->remove($like);
            $manager->flush();

            return $this->json([
                'code' => 200,
                'message' => 'Like bien supprimé',

                'likes' => $likeRepository->count(['post' => $publication])
            ], 200);
        }

        $like= new  PostLike();
        $like->setPost($publication)
            ->setUser($user);

        $manager->persist($like);
        $manager->flush();


        return $this->json([
            'code' => 200,
            'message' => 'Like bien ajouté',
            'likes' => $likeRepository->count(['post' => $publication])
        ], 200);
    }
}
